# The beauty of this CI setup is that it will build any valid DOCKERFILE by setting a few variables.
# See how at https://github.com/firepress-org/rclone-in-docker/blob/master/README-CI.md
#
# GNU v3 | Please credit the author if you are re-using some of it :-p
# by Pascal Andy | https://pascalandy.com/blog/now/

name: docker_build_ci
on:
  pull_request:
  push:
  schedule:
    - cron:  '0 8 * * *'
    # everyday at 8 am
jobs:

  Job1:
    name: Job 1/3
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Define variables
        run: |
          # Set these variables to push on Docker hub:
          echo "devmtl" > DOCKERHUB_USER
          echo "Dockerfile" > DOCKERFILE_NAME
          #
          # Set these variables to push on Github Package Registry (GPR)
          echo "firepress" > GITHUB_USER
          echo "firepress-org" > GITHUB_ORG
          echo "registry" > GITHUB_REGISTRY
          #
          # Logically defined
          cat Dockerfile | grep APP_NAME= | head -n 1 | grep -o '".*"' | sed 's/"//g' > APP_NAME
          cat Dockerfile | grep VERSION= | head -n 1 | grep -o '".*"' | sed 's/"//g' > VERSION
          date -d "-4 hours" "+%Y-%m-%d_%HH%Ms%S" > DATE_IT
          git rev-parse --short HEAD > SHORT_COMMIT_HASH
          echo "$(cat DOCKERHUB_USER)/$(cat APP_NAME)" > DOCKER_USER_APP
          echo "$(cat GITHUB_USER)/$(cat APP_NAME)" > GITHUB_USER_APP
          #
          # Tags are logically defined
          echo "$(cat DOCKER_USER_APP):latest" > TAG_LATEST
          echo "$(cat DOCKER_USER_APP):stable" > TAG_STABLE
          echo "$(cat DOCKER_USER_APP):$(cat VERSION)" > TAG_VERSION
          echo "$(cat DOCKER_USER_APP):$(cat VERSION)_$(cat DATE_IT)_$(cat SHORT_COMMIT_HASH)" > TAG_BEST_PRACTICE
          #
          # The way we define variables above is a hack. See why: https://bit.ly/2ZEAt6u

      - name: Build
        run: |
          # UAT is User Acceptance Testing
          echo "$(cat APP_NAME):uat" > TAG_UAT
          docker build --file $(cat DOCKERFILE_NAME) --tag $(cat TAG_UAT) .
          #
          docker build --file $(cat DOCKERFILE_NAME) --tag $(cat TAG_BEST_PRACTICE) .
          docker build --file $(cat DOCKERFILE_NAME) --tag $(cat TAG_VERSION) .
          docker build --file $(cat DOCKERFILE_NAME) --tag $(cat TAG_STABLE) .
          docker build --file $(cat DOCKERFILE_NAME) --tag $(cat TAG_LATEST) .
          #
          # build for Github Package Registry (GPR)

      - name: Test image with docker-library
        run: |
          git clone https://github.com/docker-library/official-images.git official-images
          official-images/test/run.sh $(cat TAG_UAT)

      - name: Test image with Aquasec microscanner
        run: |
          wget --retry-connrefused --waitretry=1 --read-timeout=5 --timeout=5 --tries=10 https://raw.githubusercontent.com/lukebond/microscanner-wrapper/master/scan.sh && chmod +x scan.sh
          #
          echo "The build will stop only if it finds a critical issue"
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest -q --exit-code 1 --severity CRITICAL $(cat TAG_UAT)

      - name: Logs / All tags & variables
        run: |
          echo "Check out https://hub.docker.com/r/$(cat DOCKERHUB_USER)/$(cat APP_NAME)/tags"
          echo " "
          echo "$(cat TAG_BEST_PRACTICE) < TAG_BEST_PRACTICE"
          echo "$(cat TAG_VERSION) < TAG_VERSION"
          echo "$(cat TAG_STABLE) < TAG_STABLE"
          echo "$(cat TAG_LATEST) < TAG_LATEST"
          echo " "
          echo "$(cat APP_NAME) < APP_NAME"
          echo "$(cat VERSION) < VERSION"
          echo "$(cat DOCKERFILE_NAME) < DOCKERFILE_NAME"
          echo " "
          echo "$(cat DATE_IT) < DATE_IT"
          echo "$(cat SHORT_COMMIT_HASH) < SHORT_COMMIT_HASH"
          echo "$(cat DOCKERHUB_USER) < DOCKERHUB_USER"
          echo "$(cat GITHUB_USER) < GITHUB_USER"
          echo "$(cat GITHUB_ORG) < GITHUB_ORG"
          echo "$(cat DOCKER_USER_APP) < DOCKER_USER_APP"
          echo "$(cat GITHUB_USER_APP) < GITHUB_USER_APP"
          echo "$(cat GITHUB_REGISTRY) < GITHUB_REGISTRY"

      - name: Logs / docker (inspect, history, version, info), uname
        run: |
          docker inspect $(cat TAG_UAT)
          docker history $(cat TAG_UAT) --no-trunc
          docker version
          docker info
          uname -a

      - name: Publish
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login --username $(cat DOCKERHUB_USER) --password-stdin
          docker push $(cat TAG_LATEST)
          docker push $(cat TAG_STABLE)
          docker push $(cat TAG_VERSION)
          docker push $(cat TAG_BEST_PRACTICE)
          #
          # push on Github Package Registry (GPR)
          # echo "ToDo/ docker build -t docker.pkg.github.com/$(cat GITHUB_ORG)/$(cat GITHUB_REGISTRY)/$(cat TAG_BEST_PRACTICE)"
          # echo "ToDo/ docker login docker.pkg.github.com -u $(cat GITHUB_USER) -p ${{ secrets.GPR_PASS }}"
          # echo "ToDo/ docker push docker.pkg.github.com/$(cat GITHUB_ORG)/$(cat GITHUB_REGISTRY)/$(cat TAG_BEST_PRACTICE)"

  # Push README.md on the Docker hub's "Full Description" section
  Job2:
    needs: job1
    name: Job 2/3
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Define variables
        run: |
          echo "devmtl" > DOCKERHUB_USER
          cat Dockerfile | grep APP_NAME= | head -n 1 | grep -o '".*"' | sed 's/"//g' > APP_NAME
          echo "$(cat DOCKERHUB_USER)/$(cat APP_NAME)" > DOCKER_USER_APP
      
      # Buggy at the moment :-(
      #
      #- name: Push Full Description on Dockerhub
      #  uses: docker://mpepping/docker-hub-metadata-github-action
      #  env:
      #    IMAGE: $(cat DOCKER_USER_APP)
      #    DOCKER_USERNAME: $(cat DOCKERHUB_USER)
      #    DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  Job3:
    needs: job1
    name: Job 3/3
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Afterbuild (brainstorm & use cases)
        run: |
          echo " "
          # echo "brainstorm/ notify succes on slack"
          # echo "brainstorm/ push a webhook to our cluster. The CD part of CI/CD"
          # echo "brainstorm/ SSH on on node to do X"
          # echo "brainstorm/ For webapps, do an healthcheck in prod cluster"
