# The beauty of this CI is that it will build every valid DOCKERFILE by setting a few variables.
# See how at https://github.com/firepress-org/rclone-in-docker/blob/master/README-CI.md

name: docker_build_ci
on:
  pull_request:
  push:
  schedule:
    - cron:  '0 8 * * *'
    # everyday at 8 am
jobs:

  Job1:
    name: Job 1/3
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: A) Define our variables
        run: |
          # Set these variables to push on Docker hub:
          echo "devmtl" > DOCKERHUB_USER
          echo "Dockerfile" > DOCKERFILE_NAME
          # set secret DOCKERHUB_USER in your Github account
          #
          ## Set these variables to push on Github Package Registry (GPR)
          echo "firepress" > GITHUB_USER
          echo "firepress-org" > GITHUB_ORG
          echo "registry" > GITHUB_REGISTRY
          #
          # Those variables are logically defined
          cat Dockerfile | grep APP_NAME= | head -n 1 | grep -o '".*"' | sed 's/"//g' > APP_NAME
          cat Dockerfile | grep VERSION= | head -n 1 | grep -o '".*"' | sed 's/"//g' > VERSION
          date -d "-4 hours" "+%Y-%m-%d_%HH%Ms%S" > DATE_IT
          git rev-parse --short HEAD > SHORT_COMMIT_HASH
          echo "$(cat DOCKERHUB_USER)/$(cat APP_NAME)" > DOCKER_USER_APP
          echo "$(cat GITHUB_USER)/$(cat APP_NAME)" > GITHUB_USER_APP
          #
          # The way we define vars above is a hack. See why:
          # https://twitter.com/askpascalandy/status/1166535922160230406

      - name: B1) Build image
        run: |
          # UAT is User Acceptance Testing
          echo "$(cat APP_NAME):uat" > TAG_UAT
          docker build --file $(cat DOCKERFILE_NAME) --tag $(cat TAG_UAT) .

      - name: B2) Test image with docker-library
        run: |
          git clone https://github.com/docker-library/official-images.git official-images
          official-images/test/run.sh $(cat TAG_UAT)

      - name: B3) Test image with Aquasec microscanner
        run: |
          wget --retry-connrefused --waitretry=1 --read-timeout=5 --timeout=5 --tries=10 https://raw.githubusercontent.com/lukebond/microscanner-wrapper/master/scan.sh && chmod +x scan.sh
          #
          echo "The build will stop only if it finds a critical issue"
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest -q --exit-code 1 --severity CRITICAL $(cat TAG_UAT)

      - name: C1) Log / tags and variables
        run: |
          echo "$(cat DOCKER_USER_APP):$(cat VERSION)_$(cat DATE_IT)_$(cat SHORT_COMMIT_HASH)" > TAG_BEST_PRACTICE
          echo "$(cat DOCKER_USER_APP):stable" > TAG_STABLE
          echo "$(cat DOCKER_USER_APP):latest" > TAG_LATEST
          echo "$(cat DOCKER_USER_APP):$(cat VERSION)" > TAG_VERSION
          #
          echo " "
          echo "Check out https://hub.docker.com/r/$(cat DOCKERHUB_USER)/$(cat APP_NAME)/tags"
          #
          echo " "
          echo "$(cat TAG_BEST_PRACTICE) < TAG_BEST_PRACTICE"
          echo "$(cat TAG_VERSION) < TAG_VERSION"
          echo "$(cat TAG_STABLE) < TAG_STABLE"
          echo "$(cat TAG_LATEST) < TAG_LATEST"
          #
          echo " "
          echo "$(cat APP_NAME) < APP_NAME"
          echo "$(cat VERSION) < VERSION"
          echo "$(cat DOCKERFILE_NAME) < DOCKERFILE_NAME"
          #
          echo " "
          echo "$(cat DATE_IT) < DATE_IT"
          echo "$(cat SHORT_COMMIT_HASH) < SHORT_COMMIT_HASH"
          echo "$(cat DOCKERHUB_USER) < DOCKERHUB_USER"
          echo "$(cat GITHUB_USER) < GITHUB_USER"
          echo "$(cat GITHUB_ORG) < GITHUB_ORG"
          echo "$(cat DOCKER_USER_APP) < DOCKER_USER_APP"
          echo "$(cat GITHUB_USER_APP) < GITHUB_USER_APP"
          echo "$(cat GITHUB_REGISTRY) < GITHUB_REGISTRY"

      - name: C2) Log / docker inspect
        run: docker inspect $(cat TAG_UAT)

      - name: C3) Log / docker history
        run: docker history $(cat TAG_UAT)

      - name: C4) Log / docker version and docker version info
        run: docker version && echo && docker info

      - name: C5) Log / uname
        run: uname -a

      - name: D) Build all tags
        run: |
          docker build --file $(cat DOCKERFILE_NAME) --tag $(cat TAG_BEST_PRACTICE) .
          docker build --file $(cat DOCKERFILE_NAME) --tag $(cat TAG_VERSION) .
          docker build --file $(cat DOCKERFILE_NAME) --tag $(cat TAG_STABLE) .
          docker build --file $(cat DOCKERFILE_NAME) --tag $(cat TAG_LATEST) .
          #
          # build for Github Package Registry (GPR)

      - name: E) Push to registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username $(cat DOCKERHUB_USER) --password-stdin
          docker push $(cat TAG_BEST_PRACTICE)
          docker push $(cat TAG_VERSION)
          docker push $(cat TAG_STABLE)
          docker push $(cat TAG_LATEST)
          #
          # push on GPR
          echo "ToDo/ docker build -t docker.pkg.github.com/$(cat GITHUB_ORG)/$(cat GITHUB_REGISTRY)/$(cat TAG_BEST_PRACTICE)"
          echo "ToDo/ docker login docker.pkg.github.com -u $(cat GITHUB_USER) -p ${{ secrets.GPR_PASS }}"
          echo "ToDo/ docker push docker.pkg.github.com/$(cat GITHUB_ORG)/$(cat GITHUB_REGISTRY)/$(cat TAG_BEST_PRACTICE)"

  # Push README.md on the Docker hub's "Full Description" section
  Job2:
    needs: job1
    name: Job 2/3
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: F1) Define our variables
        run: |
          echo "devmtl" > DOCKERHUB_USER
          cat Dockerfile | grep APP_NAME= | head -n 1 | grep -o '".*"' | sed 's/"//g' > APP_NAME
          echo "$(cat DOCKERHUB_USER)/$(cat APP_NAME)" > DOCKER_USER_APP
      
      # Buggy at the moment
      #
      #- name: F2) Update Dockerhub's Full Description
      #  uses: docker://mpepping/docker-hub-metadata-github-action
      #  env:
      #    IMAGE: $(cat DOCKER_USER_APP)
      #    DOCKER_USERNAME: $(cat DOCKERHUB_USER)
      #    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  Job3:
    needs: job1
    name: Job 3/3
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: G) Afterbuild (brainstorm & use cases)
        run: |
          echo " "
          # echo "brainstorm/ notify succes on slack"
          # echo "brainstorm/ push a webhook to our cluster. The CD part of CI/CD"
          # echo "brainstorm/ SSH on on node to do X"
          # echo "brainstorm/ For webapps, do an healthcheck in prod cluster"
